version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"

  test-connection:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.test
    container_name: test_connection
    environment:
      - DB_HOST=postgres
      - POSTGRES_DB=main_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: